package application;

import java.util.ArrayList;
import utilities.RecipeIngredientIF;

public class DynamicPanel extends javax.swing.JPanel {

    private int ID;
    private ArrayList<RecipeIngredientIF> ingredientList = new ArrayList<>();

    private DynamicPanel() {
    }

    public DynamicPanel(int ID) {
        this.ID = ID;
        initComponents();
    }

    public int getID() {
        return this.ID;
    }

    public void setIngredientList(ArrayList<RecipeIngredientIF> il) {
        this.ingredientList = il;
        String list = "";
        for (RecipeIngredientIF r : ingredientList)
            list += r.toString() + "\n";
        friendIngTextArea.setText(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendIngTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(198, 222, 201));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Friend");
        jLabel1.setOpaque(true);
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        friendIngTextArea.setEditable(false);
        friendIngTextArea.setColumns(20);
        friendIngTextArea.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        friendIngTextArea.setRows(5);
        jScrollPane1.setViewportView(friendIngTextArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea friendIngTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
